defmodule MediaCentaur.Settings.Preferences do
  # `top_level?` (as on `Settings.Config`): namespace-nested for cohesion,
  # but a top-level boundary so external contexts (web, Playback) can dep
  # it directly — Boundary doesn't allow deps on sub-boundaries.
  use Boundary,
    top_level?: true,
    deps: [MediaCentaur.Settings],
    exports: [
      AppsVisibility,
      AutoPlayNextEpisode,
      BooleanSetting,
      CardPlayButton,
      DiscoveryVisibility,
      IncomingBackdrop,
      LetterboxdLinks,
      LibraryBackdrop,
      LibraryCardInfo,
      SpoilerFree,
      UIScale
    ]

  @moduledoc """
  User preferences — typed accessors for the per-user display and behaviour
  settings stored in `MediaCentaur.Settings`.

  Each preference is one submodule owning its Settings key and default
  polarity. Boolean preferences are generated by
  `MediaCentaur.Settings.Preferences.BooleanSetting` (`setting_key/0`, `enabled?/0`,
  `enabled?/1`); `UIScale` is the one non-boolean preference and carries its
  own arithmetic.

  The web layer consumes these through the generic
  `MediaCentaurWeb.Live.SettingAware` on_mount trait, which seeds a socket
  assign from `enabled?/0` and re-assigns from `enabled?/1` on
  `{:setting_changed, key, value}` broadcasts — so each preference states its
  polarity exactly once, here.
  """
end
