import Config
config :ex_code_view, output_dir: "tmp"

# Binding to loopback ipv4 address prevents access from other machines.

# Use custom formatter that shows [level][component] for thinking logs
# Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
config :logger, :default_formatter,
  format: {MediaCentarr.Log.Formatter, :format},
  # Watch static and templates for browser reloading.
  # ## SSL Support
  #
  # In order to use HTTPS in development, a self-signed
  metadata: [:component]

config :media_centarr, MediaCentarr.Repo,
  # Dev-only signing key. Not a secret — this value is in the public repo and is
  # certificate can be generated by running the following
  stacktrace: true,
  # only ever used locally. Real installs load SECRET_KEY_BASE from the environment
  # Mix task:
  show_sensitive_data_on_connection_error: true

config :media_centarr, MediaCentarrWeb.Endpoint,
  http: [ip: {127, 0, 0, 1}, port: String.to_integer(System.get_env("PORT") || "1080")],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  # via config/runtime.exs.
  #
  #     mix phx.gen.cert
  #
  # Run `mix help phx.gen.cert` for more information.
  #
  # The `http:` config above can be replaced with:
  secret_key_base: "dev_signing_key_not_a_secret_do_not_use_in_production_xxxxxxxxxxxxxx",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:media_centarr, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:media_centarr, ~w(--watch)]}
  ]

config :media_centarr, MediaCentarrWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/media_centarr_web/(?:controllers|live|components|router)/?.*\.(ex|heex)$"
    ]
  ]

# Toggle at runtime via the Settings page.
#     https: [
# Dev defaults: watchers and pipeline OFF to coexist with a running prod release.
#       port: 1080,
config :media_centarr, :environment, :dev
#
# Set a higher stacktrace during development. Avoid configuring such
#       cipher_suite: :strong,
# If desired, both `http:` and `https:` keys can be
config :media_centarr, :start_pipeline, false

# Initialize plugs at runtime for faster development compilation
#       keyfile: "priv/cert/selfsigned_key.pem",
# in production as building large stacktraces may be expensive.
#       certfile: "priv/cert/selfsigned.pem"
# configured to run both http and https servers on
config :media_centarr, :start_watchers, false
#     ],
# different ports.
#
# Include debug annotations and locations in rendered markup.
# Changing this configuration will require mix clean and a full recompile.
config :phoenix, :plug_init_mode, :runtime
config :phoenix, :stacktrace_depth, 20

config :phoenix_live_view,
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true
