import Config

# Use custom formatter that shows [level][component] for thinking logs
config :logger, :default_formatter,
  format: {MediaCentarr.Log.Formatter, :format},
  metadata: [:component]

config :media_centarr, MediaCentarr.Repo,
  stacktrace: true,
  show_sensitive_data_on_connection_error: true

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :media_centarr, MediaCentarrWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: String.to_integer(System.get_env("PORT") || "1080")],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  # Dev-only signing key. Not a secret — this value is in the public repo and is
  # only ever used locally. Real installs load SECRET_KEY_BASE from the environment
  # via config/runtime.exs.
  secret_key_base: "dev_signing_key_not_a_secret_do_not_use_in_production_xxxxxxxxxxxxxx",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:media_centarr, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:media_centarr, ~w(--watch)]}
  ]

# Watch static and templates for browser reloading.
# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
config :media_centarr, MediaCentarrWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/media_centarr_web/(?:controllers|live|components|router)/?.*\.(ex|heex)$"
    ]
  ]

config :media_centarr, :environment, :dev
# Dev defaults: watchers and pipeline OFF to coexist with a running prod release.
#
config :media_centarr, :start_pipeline, false
# Toggle at runtime via the Settings page.
#     https: [
#       port: 1080,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
config :media_centarr, :start_watchers, false

# Initialize plugs at runtime for faster development compilation
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
config :phoenix, :plug_init_mode, :runtime

# Set a higher stacktrace during development. Avoid configuring such
# If desired, both `http:` and `https:` keys can be
# in production as building large stacktraces may be expensive.
# configured to run both http and https servers on
# different ports.
# Include debug annotations and locations in rendered markup.
# Changing this configuration will require mix clean and a full recompile.
config :phoenix, :stacktrace_depth, 20

config :phoenix_live_view,
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

config :visualizer, output_dir: "tmp"
