import Config

config :media_centarr, :environment, :prod

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :media_centarr, MediaCentarrWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# Do not print debug messages in production
config :logger, level: :info

# Use the same component-aware formatter as dev so thinking logs show [component]
config :logger, :default_formatter,
  format: {MediaCentarr.Log.Formatter, :format},
  metadata: [:component]

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
