defmodule MediaCentarr.Repo.Migrations.AddExtras do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:extras, primary_key: false) do
      add :entity_id,
          references(:entities, column: :id, name: "extras_entity_id_fkey", type: :uuid)

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :position, :bigint
      add :content_url, :text
      add :name, :text
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:extras, [:entity_id, :content_url],
             name: "extras_unique_entity_extra_index"
           )
  end

  def down do
    drop_if_exists unique_index(:extras, [:entity_id, :content_url],
                     name: "extras_unique_entity_extra_index"
                   )

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `extras` table without the `extras_entity_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:extras)
  end
end
