defmodule MediaCentaur.Repo.Migrations.AddWatchDirToWatchedFiles do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:watched_files) do
      add :watch_dir, :text
    end
  end

  def down do
    alter table(:watched_files) do
      remove :watch_dir
    end
  end
end
