defmodule MediaCentarr.Repo.Migrations.StripWatchedFilePipelineFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists index(:watched_files, ["state", "inserted_at"],
                     name: "watched_files_state_inserted_index"
                   )

    alter table(:watched_files) do
      remove :match_poster_path
      remove :match_year
      remove :match_title
      remove :error_message
      remove :search_title
      remove :confidence_score
      remove :tmdb_id
      remove :episode_number
      remove :season_number
      remove :parsed_type
      remove :parsed_year
      remove :parsed_title
    end
  end

  def down do
    alter table(:watched_files) do
      add :parsed_title, :text
      add :parsed_year, :bigint
      add :parsed_type, :text
      add :season_number, :bigint
      add :episode_number, :bigint
      add :tmdb_id, :text
      add :confidence_score, :float
      add :search_title, :text
      add :error_message, :text
      add :match_title, :text
      add :match_year, :text
      add :match_poster_path, :text
    end

    create index(:watched_files, ["state", "inserted_at"],
             name: "watched_files_state_inserted_index"
           )
  end
end
