defmodule MediaCentarr.Repo.Migrations.CreateReviewPendingFiles do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:review_pending_files, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :status, :text
      add :error_message, :text
      add :candidates, {:array, :map}
      add :match_poster_path, :text
      add :match_year, :text
      add :match_title, :text
      add :confidence, :float
      add :tmdb_type, :text
      add :tmdb_id, :bigint
      add :episode_number, :bigint
      add :season_number, :bigint
      add :parsed_type, :text
      add :parsed_year, :bigint
      add :parsed_title, :text
      add :watch_directory, :text
      add :file_path, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:review_pending_files, [:file_path],
             name: "review_pending_files_unique_file_path_index"
           )
  end

  def down do
    drop_if_exists unique_index(:review_pending_files, [:file_path],
                     name: "review_pending_files_unique_file_path_index"
                   )

    drop table(:review_pending_files)
  end
end
