defmodule MediaCentarr.Repo.Migrations.AddSeasonExtras do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:extras) do
      add :season_id,
          references(:seasons, column: :id, name: "extras_season_id_fkey", type: :uuid)
    end
  end

  def down do
    alter table(:extras) do
      remove :season_id
    end

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `extras` table without the `extras_season_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."
  end
end
