defmodule MediaCentarr.Repo.Migrations.AddMovieSeries do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:movies, primary_key: false) do
      add :entity_id,
          references(:entities, column: :id, name: "movies_entity_id_fkey", type: :uuid)

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :position, :bigint
      add :tmdb_id, :text
      add :aggregate_rating_value, :float
      add :url, :text
      add :content_url, :text
      add :content_rating, :text
      add :director, :text
      add :duration, :text
      add :date_published, :text
      add :description, :text
      add :name, :text
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:movies, [:entity_id, :tmdb_id], name: "movies_unique_entity_movie_index")

    alter table(:images) do
      add :movie_id, references(:movies, column: :id, name: "images_movie_id_fkey", type: :uuid)
    end

    create unique_index(:images, [:movie_id, :role], name: "images_unique_movie_role_index")
  end

  def down do
    drop_if_exists unique_index(:images, [:movie_id, :role],
                     name: "images_unique_movie_role_index"
                   )

    alter table(:images) do
      remove :movie_id
    end

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `images` table without the `images_movie_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop_if_exists unique_index(:movies, [:entity_id, :tmdb_id],
                     name: "movies_unique_entity_movie_index"
                   )

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `movies` table without the `movies_entity_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:movies)
  end
end
