defmodule MediaCentaur.Repo.Migrations.InitialResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:watched_files, primary_key: false) do
      add :entity_id,
          references(:entities, column: :id, name: "watched_files_entity_id_fkey", type: :uuid)

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :error_message, :text
      add :state, :text
      add :confidence_score, :float
      add :tmdb_id, :text
      add :episode_number, :bigint
      add :season_number, :bigint
      add :parsed_type, :text
      add :parsed_year, :bigint
      add :parsed_title, :text
      add :file_path, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:seasons, primary_key: false) do
      add :entity_id,
          references(:entities, column: :id, name: "seasons_entity_id_fkey", type: :uuid)

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :name, :text
      add :number_of_episodes, :bigint
      add :season_number, :bigint
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:images, primary_key: false) do
      add :entity_id,
          references(:entities, column: :id, name: "images_entity_id_fkey", type: :uuid)

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :extension, :text
      add :content_url, :text
      add :url, :text
      add :role, :text
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:identifiers, primary_key: false) do
      add :entity_id,
          references(:entities, column: :id, name: "identifiers_entity_id_fkey", type: :uuid)

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :value, :text
      add :property_id, :text
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:episodes, primary_key: false) do
      add :season_id,
          references(:seasons, column: :id, name: "episodes_season_id_fkey", type: :uuid)

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :content_url, :text
      add :duration, :text
      add :description, :text
      add :name, :text
      add :episode_number, :bigint
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:entities, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :pending_write, :boolean
      add :aggregate_rating_value, :float
      add :number_of_seasons, :bigint
      add :content_rating, :text
      add :director, :text
      add :duration, :text
      add :url, :text
      add :content_url, :text
      add :genres, {:array, :text}
      add :date_published, :text
      add :description, :text
      add :name, :text
      add :type, :text
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:watched_files, [:file_path],
             name: "watched_files_unique_file_path_index"
           )
  end

  def down do
    drop_if_exists unique_index(:watched_files, [:file_path],
                     name: "watched_files_unique_file_path_index"
                   )

    drop table(:entities)

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `episodes` table without the `episodes_season_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:episodes)

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `identifiers` table without the `identifiers_entity_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:identifiers)

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `images` table without the `images_entity_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:images)

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `seasons` table without the `seasons_entity_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:seasons)

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `watched_files` table without the `watched_files_entity_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:watched_files)
  end
end
