defmodule MediaCentarr.Repo.Migrations.AddChangeEntries do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:change_entries, primary_key: false) do
      add :inserted_at, :utc_datetime_usec, null: false
      add :kind, :text, null: false
      add :entity_type, :text, null: false
      add :entity_name, :text, null: false
      add :entity_id, :uuid, null: false
      add :id, :uuid, null: false, primary_key: true
    end
  end

  def down do
    drop table(:change_entries)
  end
end
