defmodule MediaManager.Repo.Migrations.AddPerformanceIndexes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:watched_files, ["state", "inserted_at"],
             name: "watched_files_state_inserted_index"
           )

    create index(:identifiers, ["entity_id"], name: "identifiers_entity_id_index")
  end

  def down do
    drop_if_exists index(:identifiers, ["entity_id"], name: "identifiers_entity_id_index")

    drop_if_exists index(:watched_files, ["state", "inserted_at"],
                     name: "watched_files_state_inserted_index"
                   )
  end
end
