defmodule MediaCentaur.Repo.Migrations.AddWatchProgress do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:watch_progress, primary_key: false) do
      add :entity_id,
          references(:entities, column: :id, name: "watch_progress_entity_id_fkey", type: :uuid)

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :last_watched_at, :utc_datetime
      add :completed, :boolean
      add :duration_seconds, :float
      add :position_seconds, :float
      add :episode_number, :bigint, null: false
      add :season_number, :bigint, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:watch_progress, [:entity_id, :season_number, :episode_number],
             name: "watch_progress_unique_playable_item_index"
           )
  end

  def down do
    drop_if_exists unique_index(:watch_progress, [:entity_id, :season_number, :episode_number],
                     name: "watch_progress_unique_playable_item_index"
                   )

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `watch_progress` table without the `watch_progress_entity_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:watch_progress)
  end
end
