defmodule MediaCentaur.Repo.Migrations.AddWatchedFilesIndexes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:watched_files, ["watch_dir", "state"],
             name: "watched_files_watch_dir_state_index"
           )

    create index(:watched_files, ["entity_id"], name: "watched_files_entity_id_index")
  end

  def down do
    drop_if_exists index(:watched_files, ["entity_id"], name: "watched_files_entity_id_index")

    drop_if_exists index(:watched_files, ["watch_dir", "state"],
                     name: "watched_files_watch_dir_state_index"
                   )
  end
end
