defmodule MediaCentarr.Repo.Migrations.AddAbsentStateToWatchedFiles do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:watched_files) do
      add :absent_since, :utc_datetime_usec
    end
  end

  def down do
    alter table(:watched_files) do
      remove :absent_since
    end
  end
end
