defmodule MediaCentaur.Repo.Migrations.AddMatchFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:watched_files) do
      add :match_title, :text
      add :match_year, :text
      add :match_poster_path, :text
    end
  end

  def down do
    alter table(:watched_files) do
      remove :match_poster_path
      remove :match_year
      remove :match_title
    end
  end
end
