defmodule MediaCentarr.Repo.Migrations.AddSearchTitleToWatchedFiles do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:watched_files) do
      add :search_title, :text
    end
  end

  def down do
    alter table(:watched_files) do
      remove :search_title
    end
  end
end
