defmodule MediaCentarr.Repo.Migrations.CleanupEnumsAndDefaults do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:entities) do
      remove :pending_write
    end
  end

  def down do
    alter table(:entities) do
      add :pending_write, :boolean
    end
  end
end
