defmodule MediaCentaur.Repo.Migrations.AddExtraProgress do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:extra_progress, primary_key: false) do
      add :entity_id,
          references(:entities, column: :id, name: "extra_progress_entity_id_fkey", type: :uuid),
          null: false

      add :extra_id,
          references(:extras, column: :id, name: "extra_progress_extra_id_fkey", type: :uuid),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :last_watched_at, :utc_datetime
      add :completed, :boolean
      add :duration_seconds, :float
      add :position_seconds, :float
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:extra_progress, [:extra_id], name: "extra_progress_unique_extra_index")
  end

  def down do
    drop_if_exists unique_index(:extra_progress, [:extra_id],
                     name: "extra_progress_unique_extra_index"
                   )

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `extra_progress` table without the `extra_progress_extra_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `extra_progress` table without the `extra_progress_entity_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:extra_progress)
  end
end
