defmodule MediaCentaur.Repo.Migrations.AddUniqueConstraints do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:seasons, [:entity_id, :season_number],
             name: "seasons_unique_entity_season_index"
           )

    create unique_index(:images, [:entity_id, :role], name: "images_unique_entity_role_index")

    create unique_index(:episodes, [:season_id, :episode_number],
             name: "episodes_unique_season_episode_index"
           )
  end

  def down do
    drop_if_exists unique_index(:episodes, [:season_id, :episode_number],
                     name: "episodes_unique_season_episode_index"
                   )

    drop_if_exists unique_index(:images, [:entity_id, :role],
                     name: "images_unique_entity_role_index"
                   )

    drop_if_exists unique_index(:seasons, [:entity_id, :season_number],
                     name: "seasons_unique_entity_season_index"
                   )
  end
end
