defmodule MediaCentarr.Repo.Migrations.AddEpisodeImages do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:images) do
      add :episode_id,
          references(:episodes, column: :id, name: "images_episode_id_fkey", type: :uuid)
    end

    create unique_index(:images, [:episode_id, :role], name: "images_unique_episode_role_index")
  end

  def down do
    drop_if_exists unique_index(:images, [:episode_id, :role],
                     name: "images_unique_episode_role_index"
                   )

    alter table(:images) do
      remove :episode_id
    end

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `images` table without the `images_episode_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."
  end
end
